import { CAROUSEL_IMAGE_URLS, WIKI_IMAGES, DUMMY_TAGS, DUMMY_COORDINATES } from "./dummy";
import { API_URL, MAIN_NAV_LINKS } from "./constants";

export {
    API_URL,
    CAROUSEL_IMAGE_URLS,
    MAIN_NAV_LINKS,
    WIKI_IMAGES,
    DUMMY_TAGS,
    DUMMY_COORDINATES
}